#!/bin/sh

#chain must exist as system default
export in_chain="input_rule"
export out_chain="output_rule"
export fwd_chain="forwarding_rule"

export device_chain="wan" # device rule name

export nq_q_chain="noquota_rule" # after qouta 0 rule run
#export mode="limitdrop"

export wan_device_name="eth0" # WAN, modem, etc Device has quota based data plan 

export quota_bytes="1073741824" # Quota in bytes

#export quota_time_mgr=1
#export time_active_config="--timestop 18:00:00 --timestart 22:59:00" # Using UTC timezone

export bytescounter="/etc/counter" # Counter or saved remain quota