#!/bin/sh

#chain must exist as system default
export in_chain="input_rule"
export out_chain="output_rule"
export fwd_chain="forwarding_rule"

#chain for every policy
export in_q_chain="quota_$in_chain"
export out_q_chain="quota_$out_chain"
export fwd_q_chain="quota_$fwd_chain"

export nq_q_chain="quota_noquota_rule" # after qouta 0 rule run
#export mode="limitdrop"

export extra_config="" # Extara iptables config

export wan_device_name="eth0" # WAN, modem, etc Device has quota based data plan 

export quota_bytes="1073741824" # Quota in bytes

#export qouta_time_mgr=1
#export time_active_config="--timestart 18:00:00 --timestop 22:59:00" # Using UTC timezone

export bytescounter="/etc/counter" # Counter or saved remain quota