#!/bin/sh 

. /etc/vars

if [ `/etc/quota.d/nft-check` -eq 1 ]; then
    ipt=iptables-nft
else
    ipt=iptables
fi

create_chain () {
    $ipt -L $1 $ext > /dev/null 2>&1
    if [ $? -gt 0 ]; then
        case $4 in 
            0)
                $ipt -N $1 $ext $3 > /dev/null 2>&1
            ;;
            *)        
                $ipt -N $1 $ext $3 > /dev/null 2>&1
                $ipt -A $2 $ext -j $1 $3 > /dev/null 2>&1        
            ;;
        esac
    fi
}

setbytecounter=0

case $1 in
    "setbytescounter")
        setbytecounter="1"
    ;;
    "disable")
        /etc/quota.d/iptables_flush
        exit 0
    ;;
    *)

    ;;
esac

for chain in $in_chain $out_chain $fwd_chain; do 
    create_chain "quota_$chain" $chain
done

for filter in "input" "output" "forwarding"; do 
    create_chain "${filter}_$nq_q_chain" "null" " " 0
done

create_chain "quota_counter" "null" "-t raw" 0

if [ 1 -eq $setbytecounter ]; then
    export bytes_counter=$bytescounter
fi

/etc/quota.d/iptables_quota2
