#!/bin/sh 

. /etc/vars

/etc/quota.d/save_bytescounter

iptables -F $nq_q_chain
iptables -X $nq_q_chain

for chain in $in_q_chain $out_q_chain $fwd_q_chain; do
    iptables -F $chain
    iptables -X $chain
    if [ qouta_time_mgr -eq 1 ]; then
        iptables -F ${chain}_ext
        iptables -X ${chain}_ext
    fi   
done