#!/bin/sh 

. /etc/vars

function append_iptables () {
    iptables -C $1 > /dev/null 2>&1
    if [ $? -eq 1 ]; then     
        iptables -A $1 > /dev/null 2>&1
    fi
}

function append_iptables_quota_reject () {
    local head="$1 -j reject"
    append_iptables "$head"
}

function append_iptables_quota_drop () {
    local head="$1 -j DROP"
    append_iptables "$head"
}

function append_iptables_quota_limit () {
    local head="$1 -m limit --limit 27/s --limit-burst 21 -j $2"
    append_iptables "$head"
}
function append_iptables_quota_time () {
    local head="$1 -m time $time_active_config -j $2"
    append_iptables "$head"
}

# param chain, sq, extra
function append_iptables_quota () 
{ 
    case $2 in
        0)  
            local head="$1 $4 -m quota2 --name quota ! --quota 0 -j $3"
            append_iptables "$head"
        ;;
        *)
            local head="$1 $4 -m quota2 --name quota ! --quota $quota_bytes -j $3"
            append_iptables "$head"
        ;;
    esac
}


# param chain, sq, direction
function append_iptables_quota_ex ()
{       
    case $1 in
        in)
            local q_chain="quota_${in_chain}"
            local c_nq_q_chain="input_${nq_q_chain}"
            local c_nq_d_chain="zone_${device_chain}_input"            
        ;;
        out)
            local q_chain="quota_${out_chain}"
            local c_nq_q_chain="output_${nq_q_chain}"
            local c_nq_d_chain="zone_${device_chain}_output" 
        ;;
        fwd)
            local q_chain="quota_${fwd_chain}"
            local c_nq_q_chain="forwarding_${nq_q_chain}"
            local c_nq_d_chain="zone_${device_chain}_forward" 
        ;;
        *)
            return;
        ;;
    esac
 
    if [ ! -z $quota_time_mgr ]; then
        local mchain="$q_chain"
        local chain="${q_chain}_ext"

        iptables -L "$chian" > /dev/null 2>&1
        if [ $? -gt 0 ]; then
            iptables -N $chain > /dev/null 2>&1                   
        fi
        append_iptables_quota_time "$mchain" "$chain" " "
    else
        local chain="$q_chain" 
        local mchain="${q_chain}_ext"
        iptables -L "$mchain" > /dev/null 2>&1
        if [ $? -eq 0 ]; then
            iptables -F $mchain > /dev/null 2>&1  
            iptables -X $mchain > /dev/null 2>&1                   
        fi    
    fi

    for dire in $3; do        
        case $dire in
            "in")
                local par="-i $wan_device_name"
            ;;
            "out")
                local par="-o $wan_device_name"
            ;;
        esac
        append_iptables_quota "$chain" "$2" "$c_nq_q_chain" "$par" 
    done 
    
    iptables -L $c_nq_d_chain > /dev/null 2>&1
    if [ $? -gt 1 ]; then
        local c_nq_d_chain="ACCEPT"
    fi

    case $mode in 
        "limitdrop") # limit speed with drop
            append_iptables_quota_limit "$c_nq_q_chain" "$c_nq_d_chain"              
            append_iptables_quota_drop "$c_nq_q_chain"                 
        ;;
        "limitreject") # limit speed with reject
            append_iptables_quota_limit "$c_nq_q_chain" "$c_nq_d_chain"                 
            append_iptables_quota_reject "$c_nq_q_chain"              
        ;;
        "reject")
            append_iptables_quota_reject "$c_nq_q_chain" 
        ;;
        *) # default drop
            append_iptables_quota_drop "$c_nq_q_chain" 
        ;;
    esac

}

case $1 in 
    "resetcounter")    
        echo $quota_bytes > $bytescounter
        export bytes_counter=$bytescounter
    ;;
esac

for chain in $in_chain $out_chain $fwd_chain; do # clean chain before add rule
    iptables -F "quota_${chain}" > /dev/null 2>&1    
done

append_iptables_quota_ex "in" 1 "in"
append_iptables_quota_ex "out" 0 "out"
append_iptables_quota_ex "fwd" 0 "in out"


if [ ! -z $bytes_counter ]; then
    cat $bytes_counter > /proc/net/xt_quota/quota
fi
