#!/bin/sh 

. /etc/vars

if [ `/etc/quota.d/nft-check` -eq 1 ]; then
    ipt=iptables-nft
else
    ipt=iptables
fi


case $1 in 
    nobackup)
    ;;
    *)
        /etc/quota.d/save_bytescounter
    ;;
esac

for chain in $in_chain $out_chain $fwd_chain; do 
    $ipt -D $chain $ext -j "quota_$chain" > /dev/null 2>&1
    $ipt -F "quota_$chain" $ext > /dev/null 2>&1
    $ipt -X "quota_$chain" $ext > /dev/null 2>&1
    if [ $quota_time_mgr -eq 1 ]; then
        $ipt -F "quota_${chain}_ext" $ext > /dev/null 2>&1
        $ipt -X "quota_${chain}_ext" $ext > /dev/null 2>&1
    fi
done

for filter in "input" "output" "forwarding"; do 
    $ipt -F "${filter}_$nq_q_chain" $ext > /dev/null 2>&1
    $ipt -X "${filter}_$nq_q_chain" $ext > /dev/null 2>&1
done
